version: "3"
services:
  generator:
    container_name: covid19-gen-datajson-shizuokapref
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./patients.py:/code/patients.py:ro
      - ./gen_newsjson.py:/code/gen_newsjson.py:ro
      - ./tests/:/code/tests:ro
      - ./bat.sh:/code/bat.sh:ro
    tty: true
