version: "3"
services:
  generator:
    container_name: covid19-gen-datajson-shizuokapref
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./dist:/code/dist
    tty: true
