version: "3"
services:
  generator:
    container_name: covid19-gen-datajson-shizuokapref
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/code/
      - nomount:/code/.venv/
      - nomount:/code/__pycache__/
      - nomount:/code/.pytest_cache/
    tty: true
volumes:
  nomount: {}
