version: "3"
services:
  generator:
    container_name: covid19-gen-datajson-shizuokapref
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/code
      - venv:/code/.venv
    tty: true
volumes:
  venv: {}