version: "3"
services:
  generator:
    container_name: covid19-data-generator-shizuokapref
    build:
      context: .
      dockerfile: Dockerfile
    # tty: true
    # restart: always
    # ファイルコピーを行う
